### ISSUE TITLE
Use of D_wrong?

### ISSUE THREAD

**Issue by eggachecat** [ratschlab/RGAN#15]
hi @corcra 
May I ask what is `D_wrong` for? It seems like that it together with variables `CS`, `D_logit_wrong`   are defined but have not been used?
And are `CG` and `CG`  always the same? Should these two merge ? I think it is reasonable that generator and discriminator share the same condition.
Thanks for your great work!

**Comment by corcra** [comment]
`D_wrong` was something we experimented with briefly, to try to force the discriminator in the RCGAN setting to pay more attention to labels. As I say in the comment,
`# the discriminator must distinguish between real data with fake labels and real data with real labels, too`
So basically, we create some incorrect labels, attach them to real samples, and reward the discriminator for saying these examples aren't real. I don't remember how well it worked, but I guess not (immediately) well because we didn't pursue it further.

Re: `CG` and `CD` (I assume you meant), in practice during training, they are pretty much the same. That is, whenever we use CD, its value is the same as CG's value. We use CG a lot more (whenever we sample from the conditional generator), but you could probably make it a single placeholder without changing the results... I think.
